# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [1]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import datetime

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [2]:
url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data'
data = pd.read_csv(url,sep='\s+', parse_dates=[[0,1,2]])
data.head()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [3]:
def fix_date(x):
    new_year = (x.year-100)
    return datetime.date(new_year,x.month, x.day)

data['Yr_Mo_Dy'] = data['Yr_Mo_Dy'].apply(fix_date)
data.head()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [4]:
# Convert date to datetime64
data['Yr_Mo_Dy'] = pd.to_datetime(data['Yr_Mo_Dy'])

data = data.set_index('Yr_Mo_Dy')
data.head()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [5]:
# Calcylates the number of missing values in each column
data.isnull().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [6]:
data.shape[1] - data.isnull().sum()

RPT     6
VAL     9
ROS    10
KIL     7
SHA    10
BIR    12
DUB     9
CLA    10
MUL     9
CLO    11
BEL    12
MAL     8
dtype: int64

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [8]:
# Calculates a mean over all means
data.mean().mean()

10.227982360836924

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [12]:
loc_stats = pd.DataFrame()

loc_stats['Min'] = data.min()
loc_stats['Max'] = data.max()
loc_stats['Mean'] = data.mean()
loc_stats['Std'] = data.std()

loc_stats

      Min    Max       Mean       Std
RPT  0.67  35.80  12.362987  5.618413
VAL  0.21  33.37  10.644314  5.267356
ROS  1.50  33.84  11.660526  5.008450
KIL  0.00  28.46   6.306468  3.605811
SHA  0.13  37.54  10.455834  4.936125
BIR  0.00  26.16   7.092254  3.968683
DUB  0.00  30.37   9.797343  4.977555
CLA  0.00  31.08   8.495053  4.499449
MUL  0.00  25.88   8.493590  4.166872
CLO  0.04  28.21   8.707332  4.503954
BEL  0.13  42.38  13.121007  5.835037
MAL  0.67  42.54  15.599079  6.699794

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [15]:
day_stats = pd.DataFrame()

day_stats['Min'] = data.min(axis=1)
day_stats['Max'] = data.max(axis=1)
day_stats['Mean'] = data.mean(axis=1)
day_stats['Std'] = data.std(axis=1)

day_stats.tail()

             Min    Max       Mean       Std
Yr_Mo_Dy
1878-12-27  8.08  40.08  16.708333  7.868076
1878-12-28  5.00  41.46  15.150000  9.687857
1878-12-29  8.71  29.58  14.890000  5.756836
1878-12-30  9.13  28.79  15.367500  5.540437
1878-12-31  9.59  27.29  15.402500  5.702483

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [28]:
data['date'] = data.index

data['year'] = data['date'].apply(lambda date: date.year)
data['month'] = data['date'].apply(lambda date: date.month)
data['day'] = data['date'].apply(lambda date: date.day)

data[data['month']==1].loc[:,'RPT':'MAL'].mean()

RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [29]:
data.query('month == 1 and day==1')

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,date,year,month,day
Yr_Mo_Dy,,,,,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,1961-01-01,1961,1,1
1962-01-01,9.29,3.42,11.54,3.50,2.21,1.96,10.41,2.79,3.54,5.17,4.38,7.92,1962-01-01,1962,1,1
1963-01-01,15.59,13.62,19.79,8.38,12.25,10.00,23.45,15.71,13.59,14.37,17.58,34.13,1963-01-01,1963,1,1
1964-01-01,25.80,22.13,18.21,13.25,21.29,14.79,14.12,19.58,13.25,16.75,28.96,21.00,1964-01-01,1964,1,1
1965-01-01,9.54,11.92,9.00,4.38,6.08,5.21,10.25,6.08,5.71,8.63,12.04,17.41,1965-01-01,1965,1,1
1966-01-01,22.04,21.50,17.08,12.75,22.17,15.59,21.79,18.12,16.66,17.83,28.33,23.79,1966-01-01,1966,1,1
1967-01-01,6.46,4.46,6.50,3.21,6.67,3.79,11.38,3.83,7.71,9.08,10.67,20.91,1967-01-01,1967,1,1
1868-01-01,30.04,17.88,16.25,16.25,21.79,12.54,18.16,16.62,18.75,17.62,22.25,27.29,1868-01-01,1868,1,1
1869-01-01,6.13,1.63,5.41,1.08,2.54,1.00,8.50,2.42,4.58,6.34,9.17,16.71,1869-01-01,1869,1,1
1870-01-01,9.59,2.96,11.79,3.42,6.13,4.08,9.00,4.46,7.29,3.50,7.33,13.00,1870-01-01,1870,1,1
1871-01-01,3.71,0.79,4.71,0.17,1.42,1.04,4.63,0.75,1.54,1.08,4.21,9.54,1871-01-01,1871,1,1
1872-01-01,9.29,3.63,14.54,4.25,6.75,4.42,13.00,5.33,10.04,8.54,8.71,19.17,1872-01-01,1872,1,1
1873-01-01,16.50,15.92,14.62,7.41,8.29,11.21,13.54,7.79,10.46,10.79,13.37,9.71,1873-01-01,1873,1,1
1874-01-01,23.21,16.54,16.08,9.75,15.83,11.46,9.54,13.54,13.83,16.66,17.21,25.29,1874-01-01,1874,1,1
1875-01-01,14.04,13.54,11.29,5.46,12.58,5.58,8.12,8.96,9.29,5.17,7.71,11.63,1875-01-01,1875,1,1
1876-01-01,18.34,17.67,14.83,8.00,16.62,10.13,13.17,9.04,13.13,5.75,11.38,14.96,1876-01-01,1876,1,1
1877-01-01,20.04,11.92,20.25,9.13,9.29,8.04,10.75,5.88,9.00,9.00,14.88,25.70,1877-01-01,1877,1,1
1878-01-01,8.33,7.12,7.71,3.54,8.50,7.50,14.71,10.00,11.83,10.00,15.09,20.46,1878-01-01,1878,1,1

### Step 13. Downsample the record to a monthly frequency for each location.

In [31]:
data.query('day==1')

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,date,year,month,day
Yr_Mo_Dy,,,,,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,1961-01-01,1961,1,1
1961-02-01,14.25,15.12,9.04,5.88,12.08,7.17,10.17,3.63,6.50,5.50,9.17,8.00,1961-02-01,1961,2,1
1961-03-01,12.67,13.13,11.79,6.42,9.79,8.54,10.25,13.29,NaN,12.21,20.62,NaN,1961-03-01,1961,3,1
1961-04-01,8.38,6.34,8.33,6.75,9.33,9.54,11.67,8.21,11.21,6.46,11.96,7.17,1961-04-01,1961,4,1
1961-05-01,15.87,13.88,15.37,9.79,13.46,10.17,9.96,14.04,9.75,9.92,18.63,11.12,1961-05-01,1961,5,1
1961-06-01,15.92,9.59,12.04,8.79,11.54,6.04,9.75,8.29,9.33,10.34,10.67,12.12,1961-06-01,1961,6,1
1961-07-01,7.21,6.83,7.71,4.42,8.46,4.79,6.71,6.00,5.79,7.96,6.96,8.71,1961-07-01,1961,7,1
1961-08-01,9.59,5.09,5.54,4.63,8.29,5.25,4.21,5.25,5.37,5.41,8.38,9.08,1961-08-01,1961,8,1
1961-09-01,5.58,1.13,4.96,3.04,4.25,2.25,4.63,2.71,3.67,6.00,4.79,5.41,1961-09-01,1961,9,1
1961-10-01,14.25,12.87,7.87,8.00,13.00,7.75,5.83,9.00,7.08,5.29,11.79,4.04,1961-10-01,1961,10,1
1961-11-01,13.21,13.13,14.33,8.54,12.17,10.21,13.08,12.17,10.92,13.54,20.17,20.04,1961-11-01,1961,11,1
1961-12-01,9.67,7.75,8.00,3.96,6.00,2.75,7.25,2.50,5.58,5.58,7.79,11.17,1961-12-01,1961,12,1
1962-01-01,9.29,3.42,11.54,3.50,2.21,1.96,10.41,2.79,3.54,5.17,4.38,7.92,1962-01-01,1962,1,1
1962-02-01,19.12,13.96,12.21,10.58,15.71,10.63,15.71,11.08,13.17,12.62,17.67,22.71,1962-02-01,1962,2,1
1962-03-01,8.21,4.83,9.00,4.83,6.00,2.21,7.96,1.87,4.08,3.92,4.08,5.41,1962-03-01,1962,3,1
1962-04-01,14.33,12.25,11.87,10.37,14.92,11.00,19.79,11.67,14.09,15.46,16.62,23.58,1962-04-01,1962,4,1
1962-05-01,9.62,9.54,3.58,3.33,8.75,3.75,2.25,2.58,1.67,2.37,7.29,3.25,1962-05-01,1962,5,1
1962-06-01,5.88,6.29,8.67,5.21,5.00,4.25,5.91,5.41,4.79,9.25,5.25,10.71,1962-06-01,1962,6,1
1962-07-01,8.67,4.17,6.92,6.71,8.17,5.66,11.17,9.38,8.75,11.12,10.25,17.08,1962-07-01,1962,7,1
1962-08-01,4.58,5.37,6.04,2.29,7.87,3.71,4.46,2.58,4.00,4.79,7.21,7.46,1962-08-01,1962,8,1
1962-09-01,10.00,12.08,10.96,9.25,9.29,7.62,7.41,8.75,7.67,9.62,14.58,11.92,1962-09-01,1962,9,1
1962-10-01,14.58,7.83,19.21,10.08,11.54,8.38,13.29,10.63,8.21,12.92,18.05,18.12,1962-10-01,1962,10,1
1962-11-01,16.88,13.25,16.00,8.96,13.46,11.46,10.46,10.17,10.37,13.21,14.83,15.16,1962-11-01,1962,11,1
1962-12-01,18.38,15.41,11.75,6.79,12.21,8.04,8.42,10.83,5.66,9.08,11.50,11.50,1962-12-01,1962,12,1
1963-01-01,15.59,13.62,19.79,8.38,12.25,10.00,23.45,15.71,13.59,14.37,17.58,34.13,1963-01-01,1963,1,1
1963-02-01,15.41,7.62,24.67,11.42,9.21,8.17,14.04,7.54,7.54,10.08,10.17,17.67,1963-02-01,1963,2,1
1963-03-01,16.75,19.67,17.67,8.87,19.08,15.37,16.21,14.29,11.29,9.21,19.92,19.79,1963-03-01,1963,3,1
1963-04-01,10.54,9.59,12.46,7.33,9.46,9.59,11.79,11.87,9.79,10.71,13.37,18.21,1963-04-01,1963,4,1
1963-05-01,18.79,14.17,13.59,11.63,14.17,11.96,14.46,12.46,12.87,13.96,15.29,21.62,1963-05-01,1963,5,1
1963-06-01,13.37,6.87,12.00,8.50,10.04,9.42,10.92,12.96,11.79,11.04,10.92,13.67,1963-06-01,1963,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1876-07-01,8.50,1.75,6.58,2.13,2.75,2.21,5.37,2.04,5.88,4.50,4.96,10.63,1876-07-01,1876,7,1
1876-08-01,13.00,8.38,8.63,5.83,12.92,8.25,13.00,9.42,10.58,11.34,14.21,20.25,1876-08-01,1876,8,1
1876-09-01,11.87,11.00,7.38,6.87,7.75,8.33,10.34,6.46,10.17,9.29,12.75,19.55,1876-09-01,1876,9,1
1876-10-01,10.96,6.71,10.41,4.63,7.58,5.04,5.04,5.54,6.50,3.92,6.79,5.00,1876-10-01,1876,10,1
1876-11-01,13.96,15.67,10.29,6.46,12.79,9.08,10.00,9.67,10.21,11.63,23.09,21.96,1876-11-01,1876,11,1
1876-12-01,13.46,16.42,9.21,4.54,10.75,8.67,10.88,4.83,8.79,5.91,8.83,13.67,1876-12-01,1876,12,1
1877-01-01,20.04,11.92,20.25,9.13,9.29,8.04,10.75,5.88,9.00,9.00,14.88,25.70,1877-01-01,1877,1,1
1877-02-01,11.83,9.71,11.00,4.25,8.58,8.71,6.17,5.66,8.29,7.58,11.71,16.50,1877-02-01,1877,2,1
1877-03-01,8.63,14.83,10.29,3.75,6.63,8.79,5.00,8.12,7.87,6.42,13.54,13.67,1877-03-01,1877,3,1
1877-04-01,21.67,16.00,17.33,13.59,20.83,15.96,25.62,17.62,19.41,20.67,24.37,30.09,1877-04-01,1877,4,1
1877-05-01,6.42,7.12,8.67,3.58,4.58,4.00,6.75,6.13,3.33,4.50,19.21,12.38,1877-05-01,1877,5,1
1877-06-01,7.08,5.25,9.71,2.83,2.21,3.50,5.29,1.42,2.00,0.92,5.21,5.63,1877-06-01,1877,6,1
1877-07-01,15.41,16.29,17.08,6.25,11.83,11.83,12.29,10.58,10.41,7.21,17.37,7.83,1877-07-01,1877,7,1
1877-08-01,4.33,2.96,4.42,2.33,0.96,1.08,4.96,1.87,2.33,2.04,10.50,9.83,1877-08-01,1877,8,1
1877-09-01,17.37,16.33,16.83,8.58,14.46,11.83,15.09,13.92,13.29,13.88,23.29,25.17,1877-09-01,1877,9,1
1877-10-01,16.75,15.34,12.25,9.42,16.38,11.38,18.50,13.92,14.09,14.46,22.34,29.67,1877-10-01,1877,10,1
1877-11-01,16.71,11.54,12.17,4.17,8.54,7.17,11.12,6.46,8.25,6.21,11.04,15.63,1877-11-01,1877,11,1
1877-12-01,13.37,10.92,12.42,2.37,5.79,6.13,8.96,7.38,6.29,5.71,8.54,12.42,1877-12-01,1877,12,1
1878-01-01,8.33,7.12,7.71,3.54,8.50,7.50,14.71,10.00,11.83,10.00,15.09,20.46,1878-01-01,1878,1,1
1878-02-01,27.25,24.21,18.16,17.46,27.54,18.05,20.96,25.04,20.04,17.50,27.71,21.12,1878-02-01,1878,2,1
1878-03-01,15.04,6.21,16.04,7.87,6.42,6.67,12.29,8.00,10.58,9.33,5.41,17.00,1878-03-01,1878,3,1
1878-04-01,3.42,7.58,2.71,1.38,3.46,2.08,2.67,4.75,4.83,1.67,7.33,13.67,1878-04-01,1878,4,1
1878-05-01,10.54,12.21,9.08,5.29,11.00,10.08,11.17,13.75,11.87,11.79,12.87,27.16,1878-05-01,1878,5,1
1878-06-01,10.37,11.42,6.46,6.04,11.25,7.50,6.46,5.96,7.79,5.46,5.50,10.41,1878-06-01,1878,6,1
1878-07-01,12.46,10.63,11.17,6.75,12.92,9.04,12.42,9.62,12.08,8.04,14.04,16.17,1878-07-01,1878,7,1
1878-08-01,19.33,15.09,20.17,8.83,12.62,10.41,9.33,12.33,9.50,9.92,15.75,18.00,1878-08-01,1878,8,1
1878-09-01,8.42,6.13,9.87,5.25,3.21,5.71,7.25,3.50,7.33,6.50,7.62,15.96,1878-09-01,1878,9,1
1878-10-01,9.50,6.83,10.50,3.88,6.13,4.58,4.21,6.50,6.38,6.54,10.63,14.09,1878-10-01,1878,10,1
1878-11-01,13.59,16.75,11.25,7.08,11.04,8.33,8.17,11.29,10.75,11.25,23.13,25.00,1878-11-01,1878,11,1
1878-12-01,21.29,16.29,24.04,12.79,18.21,19.29,21.54,17.21,16.71,17.83,17.75,25.70,1878-12-01,1878,12,1

### Step 14. Downsample the record to a weekly frequency for each location.

In [33]:
data.loc[::7]

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,date,year,month,day
Yr_Mo_Dy,,,,,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,1961-01-01,1961,1,1
1961-01-08,10.96,9.75,7.62,5.91,9.62,7.29,14.29,7.62,9.25,10.46,16.62,16.46,1961-01-08,1961,1,8
1961-01-15,12.04,9.67,11.75,2.37,7.38,3.13,2.50,6.83,4.75,5.63,7.54,6.75,1961-01-15,1961,1,15
1961-01-22,9.59,5.88,9.92,2.17,6.87,5.50,9.38,7.04,6.34,7.50,10.88,9.92,1961-01-22,1961,1,22
1961-01-29,NaN,23.91,22.29,17.54,24.08,19.70,22.00,20.25,21.46,19.95,27.71,23.38,1961-01-29,1961,1,29
1961-02-05,22.00,16.75,19.70,11.63,14.25,12.04,13.96,15.54,13.37,13.13,19.33,14.67,1961-02-05,1961,2,5
1961-02-12,16.00,16.92,17.25,8.38,11.75,10.37,11.71,14.37,10.37,14.62,25.41,17.04,1961-02-12,1961,2,12
1961-02-19,16.17,15.59,13.70,NaN,13.50,10.96,9.62,11.83,11.58,13.67,29.63,20.54,1961-02-19,1961,2,19
1961-02-26,25.80,21.50,22.42,15.21,23.09,16.88,21.17,17.25,18.46,20.04,22.83,23.87,1961-02-26,1961,2,26
1961-03-05,11.25,17.00,10.41,10.04,15.46,11.17,5.50,10.34,11.71,10.83,11.58,14.00,1961-03-05,1961,3,5
1961-03-12,NaN,13.88,16.38,10.25,14.92,13.67,17.12,13.70,16.29,15.79,20.50,22.54,1961-03-12,1961,3,12
1961-03-19,11.42,9.46,13.46,6.17,6.83,5.79,7.75,6.50,7.04,9.38,11.29,11.34,1961-03-19,1961,3,19
1961-03-26,15.00,11.63,12.58,8.83,13.33,10.21,13.75,10.54,14.37,13.88,15.37,22.50,1961-03-26,1961,3,26
1961-04-02,7.62,4.25,5.09,3.67,4.67,6.25,5.25,4.96,6.83,7.00,10.71,13.00,1961-04-02,1961,4,2
1961-04-09,13.37,11.12,13.08,8.83,11.75,10.21,9.96,9.59,10.54,10.50,10.13,15.34,1961-04-09,1961,4,9
1961-04-16,4.71,7.00,5.09,2.33,5.21,2.96,2.88,5.17,3.37,4.46,12.67,10.17,1961-04-16,1961,4,16
1961-04-23,12.21,7.87,7.96,9.67,11.17,10.00,10.71,10.41,11.87,10.63,10.83,10.67,1961-04-23,1961,4,23
1961-04-30,11.67,11.00,9.54,5.54,9.42,5.79,5.09,8.25,6.96,6.25,12.21,8.75,1961-04-30,1961,4,30
1961-05-07,18.16,17.71,14.88,14.46,23.16,15.46,18.21,18.05,17.04,15.96,26.63,26.58,1961-05-07,1961,5,7
1961-05-14,9.25,6.54,7.04,6.00,11.46,8.12,10.04,9.96,10.04,9.75,11.12,3.33,1961-05-14,1961,5,14
1961-05-21,6.83,4.29,11.67,3.71,5.50,4.50,3.17,6.25,4.92,4.29,10.75,10.34,1961-05-21,1961,5,21
1961-05-28,9.96,7.67,6.42,3.29,7.41,3.33,5.41,6.42,4.50,5.17,11.79,8.38,1961-05-28,1961,5,28
1961-06-04,8.50,6.42,7.25,4.67,7.79,5.17,6.21,9.87,7.29,8.33,17.00,11.42,1961-06-04,1961,6,4
1961-06-11,8.29,6.83,6.04,3.29,7.33,1.87,6.25,3.13,5.41,5.21,5.37,5.96,1961-06-11,1961,6,11
1961-06-18,12.12,9.29,7.67,7.17,14.92,10.34,13.70,13.25,12.12,12.54,17.75,24.71,1961-06-18,1961,6,18
1961-06-25,9.00,8.25,9.92,5.96,13.21,8.67,11.87,12.04,10.96,13.00,14.67,15.83,1961-06-25,1961,6,25
1961-07-02,12.04,7.25,9.25,7.04,10.34,4.92,5.83,5.96,6.25,8.63,8.00,8.50,1961-07-02,1961,7,2
1961-07-09,7.29,5.71,7.67,5.37,10.63,6.00,9.46,6.38,7.54,7.71,8.21,13.00,1961-07-09,1961,7,9
1961-07-16,21.42,10.88,11.00,10.04,14.67,9.71,13.13,11.21,11.87,11.79,12.21,12.62,1961-07-16,1961,7,16
1961-07-23,3.04,3.71,12.67,3.29,6.17,2.17,2.21,3.37,4.00,3.92,4.21,5.41,1961-07-23,1961,7,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1878-06-11,8.71,5.58,8.96,3.88,6.21,5.50,8.04,4.25,7.50,8.46,8.63,16.83,1878-06-11,1878,6,11
1878-06-18,7.17,4.63,8.46,4.79,7.54,4.21,1.71,5.33,3.92,2.50,7.75,8.25,1878-06-18,1878,6,18
1878-06-25,11.83,11.08,9.08,6.08,9.87,7.71,9.33,8.92,9.67,8.33,13.54,18.00,1878-06-25,1878,6,25
1878-07-02,16.04,14.42,12.75,10.46,15.79,11.17,11.92,10.34,10.79,5.33,10.41,15.00,1878-07-02,1878,7,2
1878-07-09,8.54,7.54,6.25,3.92,8.96,6.29,4.42,6.29,6.08,1.33,10.08,6.42,1878-07-09,1878,7,9
1878-07-16,4.71,2.21,6.00,3.04,4.12,2.54,2.33,2.58,3.33,2.79,6.25,8.63,1878-07-16,1878,7,16
1878-07-23,13.96,11.50,12.71,7.08,12.83,10.13,10.08,10.37,11.42,9.83,18.16,19.92,1878-07-23,1878,7,23
1878-07-30,13.37,10.79,7.62,6.13,5.13,6.08,2.92,6.50,5.96,5.37,8.38,7.71,1878-07-30,1878,7,30
1878-08-06,9.38,8.46,8.08,4.17,8.71,5.17,6.92,2.08,6.58,4.17,7.38,10.29,1878-08-06,1878,8,6
1878-08-13,11.83,12.12,10.58,4.00,8.04,7.12,6.25,9.92,9.21,6.67,16.54,13.79,1878-08-13,1878,8,13
1878-08-20,7.79,11.58,8.63,3.96,8.50,7.50,5.41,11.04,9.46,7.38,16.96,15.04,1878-08-20,1878,8,20
1878-08-27,4.21,1.75,6.21,2.21,1.42,2.58,1.54,1.58,2.88,3.79,8.75,9.59,1878-08-27,1878,8,27
1878-09-03,4.17,5.04,3.88,0.83,1.25,4.50,4.12,1.42,4.42,3.63,5.46,6.92,1878-09-03,1878,9,3
1878-09-10,16.46,18.12,21.50,11.63,17.00,16.42,15.67,15.50,16.25,13.62,15.54,21.12,1878-09-10,1878,9,10
1878-09-17,5.25,3.46,6.38,2.54,6.04,6.83,8.25,5.37,6.87,7.54,11.04,19.92,1878-09-17,1878,9,17
1878-09-24,11.63,10.13,13.59,4.08,10.50,7.12,12.87,7.83,8.87,8.58,15.12,19.92,1878-09-24,1878,9,24
1878-10-01,9.50,6.83,10.50,3.88,6.13,4.58,4.21,6.50,6.38,6.54,10.63,14.09,1878-10-01,1878,10,1
1878-10-08,21.67,17.12,16.25,13.08,14.67,11.67,7.62,12.50,14.21,14.21,14.58,19.21,1878-10-08,1878,10,8
1878-10-15,10.83,8.33,6.42,3.75,8.38,6.04,7.41,6.50,7.79,7.96,11.92,16.79,1878-10-15,1878,10,15
1878-10-22,6.63,4.92,7.17,3.29,6.25,5.25,8.29,3.88,5.41,6.21,9.83,15.96,1878-10-22,1878,10,22
1878-10-29,9.67,10.13,10.88,5.09,8.25,6.04,3.42,5.33,7.67,8.96,18.38,17.21,1878-10-29,1878,10,29
1878-11-05,15.46,16.92,13.13,9.62,14.12,10.96,8.92,8.63,13.25,11.42,22.37,19.00,1878-11-05,1878,11,5
1878-11-12,20.41,18.88,14.17,10.41,15.50,10.08,14.96,13.50,14.25,15.59,22.63,29.04,1878-11-12,1878,11,12
1878-11-19,13.88,11.67,8.79,4.96,7.87,5.37,11.08,7.21,7.29,6.92,16.21,20.75,1878-11-19,1878,11,19
1878-11-26,9.54,8.33,7.92,1.83,6.92,3.29,8.08,3.08,3.46,3.37,8.58,11.08,1878-11-26,1878,11,26
1878-12-03,21.21,21.34,17.75,11.58,16.75,14.46,17.46,15.29,15.79,17.50,21.42,25.75,1878-12-03,1878,12,3
1878-12-10,24.92,22.54,16.54,14.62,15.59,13.00,13.21,14.12,16.21,16.17,26.08,21.92,1878-12-10,1878,12,10
1878-12-17,9.87,3.21,8.04,2.21,3.04,0.54,2.46,1.46,1.29,2.67,5.00,9.08,1878-12-17,1878,12,17
1878-12-24,8.67,5.63,12.12,4.79,5.09,5.91,12.25,9.25,10.83,11.71,11.92,31.71,1878-12-24,1878,12,24
1878-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08,1878-12-31,1878,12,31

### Step 15. Calculate the mean windspeed for each month in the dataset.  
#### Treat January 1961 and January 1962 as *different* months.
#### (hint: first find a  way to create an identifier unique for each month.)

In [50]:
data.loc[:,'RPT':'month'].groupby(['year','month']).mean()

                  RPT        VAL        ROS        KIL        SHA        BIR  \
year month
1868 1      14.733226  12.829032  12.294194   7.849032  12.262581   7.133226
     2      12.294828  10.802759  11.742069   5.358966   9.673448   4.635517
     3      14.451613  11.906452  11.720645   8.480323  12.782903   8.292581
     4      12.350667  11.012333  10.692667   7.543333  11.969667   7.690000
     5      10.732903   9.687742   9.768387   5.931613  10.203871   5.337742
     6       8.725667   8.627000   8.621333   5.857000   9.984333   4.884000
     7       7.198710   5.700645   8.124194   4.385806   7.524194   3.491613
     8       9.231935   6.870323  13.075161   6.074839   8.954516   4.835484
     9      12.137000  11.160667  12.008000   6.886000  11.718667   6.497333
     10     12.521290  11.755484  11.235161   6.433871  11.381935   6.554516
     11     14.604000  14.257333  14.422333   6.828000  13.046333   8.008667
     12     13.090645  11.132903  13.237742   6.070000   9.675161   5.445484
1869 1      12.824839  12.113871  11.403871   6.708710  10.557097   5.926452
     2      13.504643  10.426786  14.240714   7.326786  11.314643   5.482857
     3      10.398710   8.533226  12.277419   6.125161   9.618065   4.942581
     4      12.591333   9.769333  10.828000   6.937333  11.304667   5.578000
     5       9.419032   7.941935   9.298387   5.137097   8.618710   5.391935
     6       9.360333   8.390333   9.584333   5.098667   8.344000   7.484333
     7       9.518065   8.880645   8.515161   5.415484   9.453871   6.744194
     8      11.567419   9.656774   9.192581   5.661935   9.667097   6.407097
     9       8.544333   7.146000  10.698000   4.161667   8.561333   4.934000
     10     10.640968  10.424194  10.522581   5.803548  11.545161   7.075484
     11     12.462000  11.430667  12.141333   5.499667   9.828667   6.710000
     12     13.335806  11.969032  12.433226   5.446129   9.766129   7.532581
1870 1      13.152581  11.731935  13.083871   5.810968   9.507742   8.040323
     2      14.820714  13.776071  12.643929   6.894643  11.923929   7.954643
     3      14.941613  11.496129  13.180968   7.494194  11.484194   8.242581
     4      14.733333  11.843667  12.711333   7.316667  10.938333   8.707333
     5      10.185161   9.154194   9.720323   5.639677  10.465484   7.879355
     6      10.043000   7.848333  10.693000   5.109000   9.105333   6.170333
...               ...        ...        ...        ...        ...        ...
1965 7       9.547419   8.119032   9.331935   5.605161   8.650000   5.441935
     8      11.567097   9.874839  10.232903   6.620323  11.235484   7.770000
     9      11.806000   9.588000  10.508333   6.357000   9.810000   6.274000
     10     12.419677  10.436452  10.958710   5.965161   9.569032   7.004516
     11     15.062333  12.166333  15.034667   8.019333  11.875667   8.237000
     12     14.967742  13.641935  12.678065   7.661935  12.722581   8.398710
1966 1      15.834839  13.283226  15.136452   8.659355  12.968065   9.163548
     2      17.111071  15.161786  15.554286   9.524286  15.817143  10.390714
     3      13.061613  10.668710  10.784516   8.182903  12.973871   9.167419
     4      15.808000  14.762000  14.413667   9.320333  14.252333  10.376000
     5      13.535806  12.141935  11.455161   7.443548  11.396129   8.291290
     6      10.832000   9.380333  10.663000   5.984333   8.200000   6.340667
     7      12.247419   9.312581   9.941613   6.716452  11.097097   6.566774
     8      10.571290   9.087419   9.821935   5.355806   9.471613   5.110323
     9      11.052333   9.372333   9.630667   4.881000   9.975000   5.575000
     10     11.849355   9.400645  11.537419   5.596774   9.331290   4.967419
     11     13.814333  11.779000  13.142333   7.227667  10.957333   7.051667
     12     16.103226  14.655161  12.500968   9.403548  15.485161  10.715484
1967 1      13.736129  11.470968  11.537419   6.928065  10.833548   6.730323
     2      14.510357  13.636786  13.610357   8.434643  14.155714   9.321429
     3      15.807097  13.005806  13.013226  10.170323  14.378710  10.836129
     4      12.338000  10.282333  13.357667   8.420333  11.224333   7.222333
     5      13.118710  12.039677  13.742581   7.747097  11.879032   7.519355
     6       9.328667   7.702667   9.014333   4.982333   9.664333   5.224333
     7       9.762258   9.134516   9.916774   5.260000  10.299032   6.173226
     8      10.428065   8.672903   8.974194   5.598710  10.604516   6.513226
     9      13.482667  11.475667  11.373667   6.955667  11.052667   7.428333
     10     16.318065  14.990000  14.032258   8.198065  14.456452   9.383871
     11     11.487667   9.615000  11.110000   6.161667  10.008333   5.707667
     12     12.560645   9.963871  11.303548   6.922903  11.109032   6.421290

                  DUB        CLA        MUL        CLO        BEL        MAL
year month
1868 1      12.395806   9.225806   9.415484   9.255161  14.213871  19.095484
     2       8.494828   6.803103   6.000690   6.318276   9.998621  14.467931
     3      12.452903  10.838710   9.569032  12.362581  16.263871  17.922258
     4       8.959667   9.348000   7.376000   9.049333  12.479000  15.338667
     5       6.974516   7.877097   5.458710   6.508065  12.545161  13.442581
     6       6.462333   7.005667   5.206333   5.236333  12.202000  10.843333
     7       5.817097   5.230323   4.780323   4.416452   9.455161  10.154194
     8       6.752903   6.429677   5.882258   4.733548  10.793226   9.819032
     9       9.476000   8.504000   7.781333   7.584000  12.900333  13.583667
     10      8.357742   9.450645   8.102258   8.370968  14.871935  16.388065
     11     10.813000  11.214333   9.175333  10.901667  15.818667  20.313000
     12      9.338710   7.143548   7.893226   9.208065  12.050323  18.806452
1869 1       9.882903   8.375161   8.378065   9.515484  13.410000  16.957742
     2      10.983929   8.747143   8.994286   9.081071  14.334643  19.786786
     3       9.193226   8.503226   8.376129   7.800968  10.394194  16.420000
     4       9.383333   8.141667   9.201333   8.370333  11.905667  14.124000
     5       6.309032   5.752581   5.907419   6.317419   9.332258  11.794839
     6       6.446333   6.134333   6.597667   6.042333  10.917000  11.186333
     7       7.854839   7.056774   8.286129   7.782581  14.050968  15.400323
     8       7.070323   6.366452   7.568065   7.800323  11.952258  13.715161
     9       7.120333   6.839000   6.089333   6.203333  11.665000  14.972333
     10      8.483871   9.713226   8.495806   8.717419  15.348387  17.298710
     11     10.166333   8.304667   8.458000   7.864667  14.758667  20.094667
     12     10.076774   8.656774   8.801935   7.603226  13.511613  17.707097
1870 1       9.843226   8.834194   8.407097   7.626452  12.403871  17.192903
     2      11.837857   9.223214  10.339643   8.415357  14.899643  18.016786
     3      12.160968  10.082581  10.936774   9.710645  15.041290  19.093226
     4      11.171667   9.249667  10.004333  10.178333  13.237000  16.899667
     5       8.982258   8.938387   9.251935   8.784516  13.989355  15.335161
     6       6.945667   6.983333   7.389000   6.534333  10.913333  11.817333
...               ...        ...        ...        ...        ...        ...
1965 7       8.527419   7.349355   6.989032   8.382903  10.341290  13.484194
     8      10.725806   8.931290   8.054194   9.940323  13.175484  16.014839
     9       8.296333   8.176667   6.518000   9.024333  12.659000  14.937667
     10      8.787097   8.039677   6.876774   8.898387  12.372581  14.594194
     11     13.396333   9.779333   9.344667  11.450333  13.570667  20.715667
     12     11.627419   9.155806   8.575161  10.438710  14.518065  15.506129
1966 1      12.150000  10.475806   8.750645  10.739677  14.074516  15.554194
     2      13.261429  12.716429  10.302143  13.464286  17.433929  20.116071
     3      13.188387  10.016452   9.967742  12.190968  16.758065  18.443226
     4      13.755000  12.893000  10.888333  11.970667  16.940667  21.154000
     5       9.680323   8.689677   8.456774   9.880968  14.515806  13.913871
     6       7.656000   5.949000   6.986667   8.208000  11.288333  11.303667
     7       7.641935   7.203548   8.067097   8.143548  12.133226  13.585484
     8       7.206129   6.601613   6.268065   6.478387  10.905161  11.572258
     9       7.303000   6.816333   6.158000   7.483333  11.983667  13.094667
     10      7.933871   5.396452   5.730323   7.399355  11.251613  15.240323
     11     11.816000   8.219000   8.483333  10.292333  15.567000  20.938333
     12     15.567419  11.372258  12.237419  11.297419  18.603226  21.180323
1967 1       9.787419   7.474839   7.627097  10.169032  13.457742  17.124516
     2      13.087500  10.497143   9.903929  13.056786  17.190357  19.981429
     3      17.430323  12.684516  13.376774  14.064194  19.851935  23.816129
     4      11.840333   8.139333   9.089667  10.097000  13.389000  16.747333
     5      10.462258   9.311935   7.973226   8.896774  13.610000  14.691935
     6       7.166667   8.399667   6.240333   6.968333  11.323333  12.424333
     7       7.078387   9.323871   7.206774   8.701935  13.559677  15.374839
     8       7.747742   8.169677   6.947742   7.007097  11.398710  12.952258
     9       9.478333   9.390333   8.063667   8.069667  14.453333  14.318000
     10     12.704194  11.617742  10.214194  11.657097  19.250000  20.230323
     11      8.983000   7.946333   7.594667   7.562667  14.272000  18.067667
     12     12.128065   8.954839   9.508065   8.480968  15.589677  19.952581

[216 rows x 12 columns]

### Step 16. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [65]:
weekly = data.resample('W').agg(['min','max','mean','std'])

weekly.iloc[1:53, 0:47].head()

             RPT                                VAL                    \
             min    max       mean       std    min    max       mean
Yr_Mo_Dy
1868-01-12  5.04  17.67  11.178571  5.057217   4.71  16.62  10.517143
1868-01-19  9.79  30.29  18.058571  7.016270  13.67  22.25  16.865714
1868-01-26  4.96  25.12  12.064286  7.235613   4.67  12.04   8.227143
1868-02-02  7.79  22.67  15.915714  4.836224   7.21  21.92  15.971429
1868-02-09  6.29  21.75  11.101429  5.333512   3.04  22.08   9.040000

                        ROS           ...        CLO                       \
                 std    min    max    ...        max       mean       std
Yr_Mo_Dy                              ...
1868-01-12  4.658289   5.37  20.17    ...      12.46   6.637143  3.871751
1868-01-19  3.730692  10.25  24.00    ...      18.66  12.361429  3.352350
1868-01-26  2.671558   3.00  14.75    ...      12.87   6.605714  4.771159
1868-02-02  5.184231   8.33  18.75    ...      13.92  10.227143  2.980177
1868-02-09  6.685277   4.04  15.67    ...      15.29   5.308571  4.662951

              BEL                                MAL
              min    max       mean       std    min    max       mean
Yr_Mo_Dy
1868-01-12   5.96  14.46   8.965714  3.293741  10.92  28.08  18.262857
1868-01-19  14.67  24.96  19.647143  3.616959  14.96  29.04  21.130000
1868-01-26   1.87  17.33  11.427143  5.480419   4.79  23.50  16.028571
1868-02-02  13.50  23.09  17.008571  3.156683  11.71  25.84  20.120000
1868-02-09   6.92  22.54  10.978571  5.568301   9.83  26.71  16.267143

[5 rows x 47 columns]